name: Validate iOS Swift Package

on:
  push:
    branches: [ main ]
    tags:
      - 'ios-v*' # Triggers when you push a tag like ios-v1.0.5
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build Swift Package
        run: swift build

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/ios-v')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
